### ISSUE TITLE
Functional difference between default:true and optout:true?

### ISSUE THREAD

**Issue by ErinPo** [KIProtect/klaro#147]
These two settings would seem to result in the same thing, namely that a tag is loaded on the first visit but can be deactivated by the user at any time. What am I missing?

**Comment by ErinPo** [comment]
Tok, tok, anybody home?

**Comment by jaller94** [comment]
### `default`
Default determines the state of an optional app, when you open the modal. It won't become active until consent is given.

### `optout`
https://github.com/KIProtect/klaro/blob/42b006ab88c316942b9dedfa23163a59f7997fcf/dist/config.js#L229-L232

This might make sense for an external script that has to load early in order to function (e.g. wrap some DOM nodes/ components), but waits for an additional call before gathering data.

**Comment by adewes** [comment]
We'll improve the documentation for this and other aspects!
