### ISSUE TITLE
"Accept" does not accept default: false ones

### ISSUE THREAD

**Issue by ChristopherWalz** [KIProtect/klaro#179]
Having the following config:

```var klaroConfig = {
	elementID: 'klaro',
	cookieName: 'klaro',
	cookieExpiresAfterDays: 365,
	privacyPolicy: privacyLink,
	apps: [
		{
			name: 'basic',
			title: 'Notwendige Cookies',
			purposes: ['basic'],
			required: true
		},
		{
			name: 'matomo',
			title: 'Matomo',
			purposes: ['analytics'],
			required: false,
			default: true,
			optOut: true,
		},
		{
			name: 'analytics',
			title: 'Google Analytics',
			purposes: ['analytics']
		}
	],
};
```

clicking on "Accept" (cm-btn cm-btn-sm cm-btn-success) will only enable "basic" and "matomo", but not "analytics".
How can I have an "Accept all" button which accepts all cookies if the user doesn't open the "Customize..." modal?

I don't want to put `default: true` for analytics, because then the slider is enabled when opening the "Cusomize..." modal.

**Comment by adewes** [comment]
That's what we created the "Accept All" workflow for :)

You can enable it by setting `acceptAll: true` in you config, I think it's exactly what you want.

We will probably make this the default workflow in the future, we don't enable it by default due to backwards compatibility now.

We are in the process of improving the documentation as well.

Let me know if that solves your problem!

**Comment by ChristopherWalz** [comment]
Yes thanks that solves the problem. I actually used `acceptAll: true` and was wondering why it is not working until I realized that I have not updated to the newest version ;)
