### ISSUE TITLE
Cookie "coockiename" will be soon rejected because it has the “sameSite” attribute

### ISSUE THREAD

**Issue by Flaschenzug** [kiprotect/klaro#214]
**Current behavior**After accepting the cookies I get this console.log: 
> Cookie "coockiename" will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies new.

**Steps to reproduce**
Seems to be a Goolge / Chrome / Firefox thing. Found this article: https://github.com/rails/rails/issues/39190

I can reproduce it on the site of the project:
https://klaro.kiprotect.com/

Using Firefox 76.0.1

**Comment by creopard** [comment]
Try this in your .htaccess file:
`php_value session.cookie_secure 1`
This will set the secure attribute on cookies, i.e.only allow them via HTTPS.

**Comment by hd7b** [comment]
Same problem here. With the .htaccess entry the warning in the console remains.
Any solution yet?

**Comment by adewes** [comment]
Hi @hd7b, @creopard, @Flaschenzug, thanks for reporting this. Klaro now explicitly sets the Klaro cookie value to `SameSite=Lax`in order to conform with the upcoming change. The Klaro cookie doesn't contain sensitive or personal information and does not have any security implications, so we didn't enable HTTPsOnly or `SameSite=Strict` for now, we might make this configurable in the future though.
