### ISSUE TITLE
Klaro as a consent management platform and records of consent.

### ISSUE THREAD

**Issue by DoruCii** [KIProtect/klaro#219]
Hi! Klaro is a wonderful tool. However, unless integrated with a record consent tool, it fails to achieve its purposes. According to the European Data Protection Board:
"For instance, the controller may keep a record of consent statements received, so he can show how
consent was obtained when consent was obtained and the information provided to the data subject
at the time shall be demonstrable. The controller shall also be able to show that the data subject was informed and the controller´s workflow met all relevant criteria for valid consent. The rationale
behind this obligation in the GDPR is that controllers must be accountable with regard to obtaining
valid consent from data subjects and the consent mechanisms they have put in place. For example, in an online context, a controller could retain information on the session in which consent was expressed, together with documentation of the consent workflow at the time of the session, and a copy of the information that was presented to the data subject at that time. **It would not be sufficient to merely refer to a correct configuration of the respective website.**"
Users relying on this tool should now that, without keeping records of the consent, they are in breach of GDPR. This is called the doctrine of proof of concept. However, this doctrine is not compliant under GDPR.  You can't claim that, because Klaro blocks third party cookies, you are compliant. So, are the developer looking into any functionality that could keep a record of consent?

**Comment by adewes** [comment]
Thanks for your issue. You are correct that within GDPR a data controller who relies on consent for processing personal data needs to be able to prove this consent was given. However, that **does not** mean that he is obliged to store the consent on a centralized backend, in fact this would go against other principles of the GDPR (e.g. data minimisation) and would therefore not be compliant in many cases.

When using Klaro to ask anonymous (not logged-in) website users for consent it is sufficient to store their consent choice in the browser. Storing consent choices on the backend doesn't make sense as one would also need to store a cookie on the user device to link the consent choice to that particular user (as there is no other identifying information that we can use since the user is not authenticated). This would entail storing personally identifiable information on the backend as well as in the browser, which is less privacy-friendly than storing that information only in the browser. As a data controller you can still fulfill all GDPR subject rights relying on browser-stored consent choices.

For a registered user you might want to store consent choices in your own backend, e.g. in order to permanently associate it with a given user and not ask that user again and again for consent. Klaro allows you to do that as you can easily access the consent choices either by reading the respective cookie or (if the localStorage option is used) via Javascript.

We are actively participating in the legislative process for defining consent guidelines so we are confident that storing user consent on a backend is not mandated by GDPR and does not follow data minimisation guidelines.

Can you provide a reference to the document(s) that lead you to believe storing consent in a backend is mandated by GDPR?

**Comment by DoruCii** [comment]
Hi! Can you have a look here: https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/consent/how-should-we-obtain-record-and-manage-consent/ section "How should we record consent?", where the data owner, when challenged, should provide the record of consent. Proof of consent scenarios such as "If the user doesn't opt-in, the site won't load 3rd party cookies", are not accepted. Can you also check section 5 of the latest Guidelines 05/2020 on consent under Regulation 2016/679. The Guidelines is available here: https://edpb.europa.eu/our-work-tools/our-documents/guidelines/guidelines-052020-consent-under-regulation-2016679_en . Also, in my initial message, I outlined the following: "For example, in an **online context**, a controller **could retain information on the session in which consent was expressed**, together with documentation of the consent workflow at the time of the session, and a copy of the information that was presented to the data subject at that time. It would not be sufficient to merely refer to a correct configuration of the respective website." Thank you!

**Comment by DoruCii** [comment]
I strongly agree with your point of view, and it makes 100% sense, however, judging on the latest developments, we have to take an excessive and absurd approach.

**Comment by adewes** [comment]
Thanks for the links. I know that a lot of providers of consent management solutions are pushing their customers to store consent on their servers, which they do (in my humble opinion) mostly out of financial interests (it is easier to justify the cost of a consent manager if it requires a complex backend architecture).

In my opinion storing consent in a backend is neither required nor recommended as it doesn not follow data minimisation principles and is not commensurate for tracking pseudonymous/anonymous users on your website.

The EU institutions themselves implement consent on their websites using a cookie-based solution that stores consent on the client-side, they even have a consent kit available (will require an EU login to see the details of the kit): https://wikis.ec.europa.eu/display/WEBGUIDE/04.+Cookies

I would estimate that > 99 % of websites implement consent without relying on logging of consent choices on a backend and I have never heard of a single case where a company or organization has been reprimanded or fined for using such a workflow.

If you absolutely want to log your users' consent choices I'd recommend enabling cookie-based storage and logging relevant parameters directly with your web server. With servers like nginx for example it is easy to extract the value of the consent cookie together with relevant details like the user agent or IP address and store it on the server-side. In my humble opinion this is overkill though and not required by the going interpretation of the ePrivacy directive or GDPR.

**Comment by adewes** [comment]
Again, for workflows where consent is attached to a permanent user profile it makes sense to log it in the backend, which you can easily do by using a consent cookie.

**Comment by DoruCii** [comment]
Dear @adewes ! That's a brilliant reply! **I subscribe to your point of view**, and I've reached the same personal conclusion. 
However, the issues of non-compliance still persist, and it's irrelevant if I agree with you or not. Once again, the EDPB clarifications, instead of clearing things out, further complicate things. Instead of approaching this issue in a technical manner, with privacy-by-design and data minimization in mind, they, once again, issue a clarification that puzzles everyone. 
You are absolutely right about the practices on EU websites. But, do you think any action will be taken? Of course not. In the worst-case scenario, they will probably argue for "public interest" and call it a day! However we, the mortals :), have to deal with absurdities and contradictions. In the meantime, FB gets preferential treatment from Ireland's DPC.  
Yes indeed, the only ones benefiting from this implementation are paid consent solution providers. In their free tiers, which they advertise as fit for purpose, they don't include consent records, but they gladly offer it as part of paid tiers. Why do you offer a product that fails to deliver its main purpose?
Dear Andreas, remember the Impressum "witch hunt" era in Germany? That's exactly what's gonna happen with consent management. Give it a few months. 
Thank you for your reply!

**Comment by adewes** [comment]
Thanks for the input, I appreciate it. I don't think we'll see a lot of legal complaints regarding client-side cookie consent solutions, competition law has been revised in the last years to make such harassment (what such a practice really mostly amounts to) more difficult.

In the upcoming update of Klaro we will add better support for storing consent choices in your own backend if you decide to do so and we are committed to keeping our solution the most privacy-friendly, balanced and of course compliant way to ask for consent on websites.

**Comment by UniversalDesignz** [comment]
Interesting as we know Gov themselves don't seem to know what directions to
go and on the other side please have a look at https://www.gov.uk/
<https://www.gov.uk/>

Kindest Regards
Jay Vijay
*Universal Designz Ltd*
