### ISSUE TITLE
Add option to toggle all cookies of one purpose on/off

### ISSUE THREAD

**Issue by JochenJung** [kiprotect/klaro#225]
When purposes are:
- marketing
- analytics

It would be nice to turn on/off all marketing cookies at once. Maybe right on the initial box without opening the modal.

**Comment by intradesign** [comment]
Thanks to recent changes with the ability to insert HTML in the text area of the consentModal, you can now build links yourself that can enable or disable multiple individual apps.

```
consentModal: {
                extraHTML:"<a onClick=\"klaro.getManager().updateConsent('inlineTracker', true);klaro.getManager().updateConsent('externalTracker', true);klaro.getManager().saveAndApplyConsents();\">Activate inline and external tracker (Demo)</a>",
                description:
                    'Hier können Sie einsehen und anpassen, welche Information wir über Sie sammeln. Einträge die als "Beispiel" gekennzeichnet sind dienen lediglich zu Demonstrationszwecken und werden nicht wirklich verwendet.',
            },
```

![image](https://user-images.githubusercontent.com/21263208/88515775-83483380-cfec-11ea-983e-6805c8335fba.png)

This also allows you to enable and disable the purposes together.

Whether it works in the consentNotice, I don't know. Probably the visual feedback would be missing here.

**Comment by adewes** [comment]
Wow that's really neat :)

**Comment by adewes** [comment]
BTW we plan to add category-based consent to the official tool, there are just a few issues that need to be resolved first (e.g. how to handle backwards-compatibility).

**Comment by intradesign** [comment]
Maybe the better solution would be to provide a free switch instead of
categories, which can be named freely and in which the apps can also be
entered freely. That way you could group them by any criteria you want, not
just by the Purposes... Klaro also offers high flexibility in all other
areas.

Example: Instead of toggling all "analytics" apps, you could add a switch
that toggles all Google apps.

Like this:

switch: {
title: 'Google',
description: 'Toggle all Google related apps',
apps: ['googleAnalytics','googleMaps',googleFonts],
}

instead of this:

switch: {
title: 'Google',
description: 'Toggle all Anylytics related apps',
purposes: ['analytics'],
}

or for even more flexibility apps and purposes?

The activation of the switch could then fire updateConsent('true' (or
'false')) for the individual apps.

In this way, you could also combine the intended uses with a switch, for
example "activate all but third parties", and still be able to build the
intended uses in detail instead of combining them into 3 or 4.

I tested some other tools where the purposes were not clearly defined, but
there were overlaps, for example "3rd party" and "analytics".

That's just as an idea, I'm not a developer and don't know how to implement
that exactly.

Am Mo., 27. Juli 2020 um 18:41 Uhr schrieb Andreas Dewes <
notifications@github.com>:

**Comment by intradesign** [comment]
*In addition to my last post:*

for a current project, a Fuel Station Finder must be integrated, whose Fuel
Station information is pulled from another website (other operator), which
is displayed in a map view of Google Maps. The data provider uses Google
Analytics.

With the switch described above you could create a switch like this:

switch: {
title: 'Fuel Station Finder',
description: 'De/Activate fuel station finder',
apps: ['fuelstationData','googleMaps',GoogleAnalytics],
}

 (in simplified form)

Without the map view, a table view with filter would appear as a fallback.

Am Di., 28. Juli 2020 um 00:44 Uhr schrieb Timo Mackowiak <
timo.mackowiak@intradesign.xyz>:

**Comment by adewes** [comment]
Hey @JochenJung @intradesign , I just pushed a new release that adds a `groupByPurpose` option which will display all apps for a given purpose under an expandable group, enabling the user to enable or disable all apps in the group within a single click. Let me know what you think :) I also improved (I hope, at least) the visualization of partially selected apps in a given group, happy to get some feedback on that as well.

I managed to keep the change compatible with the previous configuration options and translations, so you don't have to do anything except set the variable to `true` (right now it's set to false).

We've also started to write a proper Klaro documentation btw, you can find it here (still a work-in-progress): https://kiprotect.com/docs/klaro. The main Klaro website will also move to the parent domain soon.
