### ISSUE TITLE
NPM klaro package has no source folder.

### ISSUE THREAD

**Issue by sowinski** [kiprotect/klaro#233]
Hi,

why there is no src folder in the klaro npm package?

https://www.npmjs.com/package/klaro

I would also like to access the SASS or at least CSS files in the package. Is this not the official package name in NPM?

Thank you

**Comment by adewes** [comment]
Hi @sowinski, there now is the CSS present in the NPM package, please see the `README` for an example of how to import the CSS from there.
I'm not sure if it's useful to include the source code in the NPM package as well, typically there is only directly importable code there. We're thinking about a way to expose the ES6 modules but in my understanding this is still experimental in Node.js.

**Comment by dahaupt** [comment]
@adewes I was also surprised to see that the **src** folder is not available. We use the `scss` files as foundation to build our own theme! 

E.g. the package of [bootstrap](https://www.npmjs.com/package/bootstrap) provides the those files, but I am not sure about the general convention.

**Comment by adewes** [comment]
Hi @dahaupt, we could include the source files of course. Is the CSS (which is included) not sufficient for you?

**Comment by dahaupt** [comment]
@adewes Yes, I guess so. At the end it's for convenience and some performance if we can edit the **scss** source code directly, instead of having to overwrite it. Personally, I do not like to overwrite CSS, when I have the possibility to change necessary lines in SCSS directly.

```

**btw**: Thanks for caring and replying that fast! Please consider adding a the **sponsoring** (https://github.com/sponsors) button or an alternative to support your work!

**Comment by adewes** [comment]
Hey no problem, I've just added the SCSS and JS files to the NPM package. They're not very big and it might be convenient to have them e.g. in order to directly import them as SCSS as you said.

Regarding the sponsorship: We're working on backend features for Klaro and a SaaS version, as soon as that's ready you can just register for a paid plan to support us :) Early contributors and supporters like you will get a special, discounted plan btw :D
