### ISSUE TITLE
Behavior of required app: Only "true" if "select all" was clicked otherwise "false"

### ISSUE THREAD

**Issue by marcsaleiko** [kiprotect/klaro#247]
**Klaro Config**

Any app with `required: true`, e.g.:

```
 apps: [ 
 {
    name: 'googleMaps',
    required: true
 }
],
```

**Steps to reproduce**

Use klaro-no-css.js

To verify the required app is always false check https://klaro.kiprotect.com/
- Visit the site and select any amount of apps and click save or accept
- Check for the state of the apps in the klaro cookie and you will discover that the required app "cloudflare" is set to false although it is required

In my setup we use the "select all" option. Do the following with any required app:
- Click "select all"
- Check for the state of the apps in klaro cookie and see your required app is now set to true and your scripts etc. were triggered. That is not consistent.

**Current behavior**

"select all" sets app to true, "save" to false

**Expected behavior**

"select all" and "save" will set app to true

Is this behavior intended? Thank you for checking this one. Have a great day!

**Comment by adewes** [comment]
Klaro uses the `default` value for every app (which is set to `false` in the example config), hence the consent state for Cloudflare is shown as `false` as well since the user never actively consented. I can see why this might be confusing and unpractical for a required app, so I changed the behavior such that the consent will be shown as `true` for apps that are required. I'm not sure if this is ideal though, maybe we should remove these apps from the consent entries altogether since the user really doesn't have a choice here, and claiming that the user has given consent for the app therefore seems wrong...

I'm thinking about cases where at first an app might be listed as required. If the user then clicks on "Accept" the consent for the app will be set to `true`. Then, if we remove the `required` flag the app consent will still be shown as true even though the user has never consented in its use.

**Comment by marcsaleiko** [comment]
@adewes thank you for fixing the issue itself (behavior is now consistent). I really understand the additional scenario you describe in your comment. If we set the consent to true it will stay true although someday in the future the app won't be "required" any more.

Maybe just an idea: 

1. What about providing an additional callback for required apps or 
2. A `required` flag in the callback, so that required apps will have the consent status "false", but the callback will be triggered anyway with an additional argument e.g. `required = true`. 

Maybe something like that to distinguish between consent given actively and required apps.
