### ISSUE TITLE
Design of the modal window

### ISSUE THREAD

**Issue by barznet** [kiprotect/klaro#251]
Is it possible to create such a design of the modal? 

<img width="765" alt="dom9" src="https://user-images.githubusercontent.com/8721373/87914126-7ec1cf00-ca70-11ea-8ff8-1ab1b2e5131a.png">

A click on "Design anzeigen" opens the list of settings, a second click closes it. 

<img width="765" alt="domsport 2020-07-20 10-05-28" src="https://user-images.githubusercontent.com/8721373/87914203-97ca8000-ca70-11ea-8e09-ae3b752ec71f.png">

Thanks.

**Comment by adewes** [comment]
We plan to add a "categories view" where you will be able to toggle whole categories of apps / cookies, this would probably be what you want to achieve here? Otherwise we intend to keep the notice as simple as possible so that it's not too obtrusive. There is the `mustConsent` option to show the modal directly at the start, this could achieve the effect you might intend.

**Comment by adewes** [comment]
Hey @barznet , I just pushed a new version that enables grouped consent (i.e. grouping apps by purpose), let me know what you think!
