### ISSUE TITLE
Use Klaro as vue.js component

### ISSUE THREAD

**Issue by PeterSchoell** [kiprotect/klaro#259]
**The problem**

We want to use Klaro in our vue.js SPA as consens manager.

**Proposed solution**

Develop a simple vue.js component.

**Frist draft of a component**
Still need some help to get ist run.

		<template>
			<div id="klaro">
				Klaro hier
				<v-btn rounded depressed @click="show">Change consent settings</v-btn>
			</div>
		</template>

		<script>
			import './klaro.css';
			import * as config from './config.js';
			import * as klaro from './klaro-no-css.js';
			export default {
				mounted() {
					console.log(klaro);
					console.log(config);
					klaro.show();
					console.log("klaro mounted");
				},
				methods: {
					show() {
						console.log("klaro show");
						klaro.show();
					},
			  }
			}
		</script>

**Comment by adewes** [comment]
Hi @PeterSchoell! Thanks for opening this issue. I just updated the build config so that we always publish the latest Klaro version on npm as well, and I've also added and [example](../tree/master/examples/klaro-and-webpack) to show how to import and use Klaro as a Node module. Can you have a look at that and let me know if that solves your problem? The new version should be on NPM shortly as well.

**Comment by PeterSchoell** [comment]
> Hi @PeterSchoell! Thanks for opening this issue. I just updated the build config so that we always publish the latest Klaro version on npm as well, and I've also added and [example](../tree/master/examples/klaro-and-webpack) to show how to import and use Klaro as a Node module. Can you have a look at that and let me know if that solves your problem? The new version should be on NPM shortly as well.

Perfect! The problem was loading the config file.
