### ISSUE TITLE
How to use i18ns

### ISSUE THREAD

**Issue by net4u** [KIProtect/klaro#27]
Hi,

I found that exists translation for Romanian (in src/translations/ro.yml file), but I really don't understand how to use it.

**Comment by net4u** [comment]
Solved.

**Comment by adewes** [comment]
@net4u great, sorry for the delay, I'm currently on the road! I'm writing the answer here so that it might be useful to other even though you already solved it:
* The language can be set directly in the config via the `lang` attribute, if this is not set it will fall back to the global `language` variable, if that doesn't exist it will look for the `lang` attribute of the HTML document and if that also doesn't exist it will fall back to `en` as a default.
