### ISSUE TITLE
Implementation and Execution

### ISSUE THREAD

**Issue by UniversalDesignz** [kiprotect/klaro#274]
#Hey!

Can on of you kindly send the the instruction to implement the code as I am having a issue there the the consent box shows up but doesn't faction as it seem.

https://a.cl.ly/xQuLYydg

I can't find any clear instruction for this.

Thank you in advance.

Kindest Regards
Jay Vijay

If you have a support question, feel free to ask it here.

Before submitting a new question, please make sure you:

- Read [the introduction](https://klaro.kiprotect.com).
- Searched opened and closed [GitHub issues](https://github.com/KIProtect/klaro/issues?utf8=%E2%9C%93&q=is%3Aissue).

**Comment by adewes** [comment]
Could you please at least post any errors you're seeing on the debug console? It's not possible to help you just by looking at the screenshot of the consent manager.

**Comment by UniversalDesignz** [comment]
Hi @adewes 

Thanks for getting back me. Sorry for sure I don't see any errors. Please find both links below.

https://web.universaldesignz.co.uk/klaro-MFDisclmr

https://web.universaldesignz.co.uk/UDtmp

**Comment by adewes** [comment]
It seems Klaro itself is working correctly, I can open the modal by typing `klaro.show(undefined, true)`.  However, mouse events don't seem to get passed on to Klaro. There are a ton of scripts and event handlers active on your page, I would deactivate to see what's causing the problem. There is an `ast-mouse-clicked` class added to the page when the button gets clicked, this might be an event handler that does not propagate the event to Klaro. Hope this helps you to debug this!

I'm closing this since it's clearly not a Klaro issue.
