### ISSUE TITLE
Release thunderstorm

### ISSUE THREAD

**Issue by instantflorian** [kiprotect/klaro#281]
Hi,

no offense, it's great that you're developing the script so actively, but publishing one release after the other within a few days or even within hours makes it inpossible to stay up to date with own implementations/installations of klaro. 
I think you should not create a tag and a release after every single commit.
At least it would be helpful if the releases were (meaningfully) tagged (pre-release, stable etc.)

**Comment by instantflorian** [comment]
Hi,
thanks for your reply.
I must confess that I have lost connection to Klaro since v. 0.34, upon which I had paid a developer to write a plug-in for my CMS project. I just notice that since then nearly everything has changed and even no "usual" CSS files are shipped any longer (and also no usable klaro.js...?). So we will have to stick to that old version and won't care about upcoming releases.

**Comment by adewes** [comment]
Hi @instantflorian! We tried to keep Klaro backwards-compatible with earlier versions, the config files for version 0.34 should still work with the new release (except for a few translation strings maybe). We distribute `klaro.js` and all associated files through two channels: NPM and our CDN (we might also add them to our Github again, we removed them since they were not always up-to-date, we should probably just improve our process around that). You can of course still build all the files yourself as well. For the NPM version, simply run

    npm install klaro

This will give you a directory with `klaro.js`, `klaro-no-css.js` (no CSS version) and `klaro.css` as well as `klaro.min.css` files in the `dist` folder. In addition, we also include the SCSS & JS files in the `src` folder, so you can directly import them (useful if you e.g. use Webpack for bundling).

We also host all release files mentioned above on our CDN, so you can e.g. download a specific Klaro version from http://cdn.kiprotect.com/klaro/latest/klaro.js or http://cdn.kiprotect.com/klaro/latest/klaro.css (you can replace `latest` with a specific version like `v0.4.18`). The directories provide a JSON index so you can e.g. automate downloading new releases (querying https://cdn.kiprotect.com/klaro/v0.4.18/ will give you a JSON list of all files in the directory).

We also have a [releases.yml](https://github.com/kiprotect/klaro/blob/master/releases.yml) file that contains a machine-readable changelog and hashes of all tagged Klaro builds, you can use that to e.g. automate updating (there are tags for e.g. breaking releases or security updates).

We also generate a release log from this file in our documentation: https://kiprotect.com/docs/klaro/releases. Let me know if there's anything we can improve, we're happy to help you integrate Klaro into your CMS project and fix breaking changes.

**Comment by adewes** [comment]
Hey @instantflorian, distribution files are available in the repo again.

**Comment by instantflorian** [comment]
That's great, thank you so much.
