### ISSUE TITLE
Default translations with "åäö" not decoded properply for FI and SV at least

### ISSUE THREAD

**Issue by tommy-snellman** [kiprotect/klaro#298]
**Steps to reproduce**
View the notice in FI or SV and don't supply translations in the config file.

**Current behavior**
For the SV and FI translation the default text where there are characters "åäö" are not displayed correctly:
![image](https://user-images.githubusercontent.com/3628923/93583316-5ab93600-f9ac-11ea-8515-463ad89a856d.png)
And the FI translation has even some missing translations:
![image](https://user-images.githubusercontent.com/3628923/93734599-92112800-fbe2-11ea-8f55-ef3dee0f44bc.png)

But for a field where I have supplied a translation it is displayed correctly:
![image](https://user-images.githubusercontent.com/3628923/93583383-73c1e700-f9ac-11ea-8552-1f4e112c99d0.png)

**Expected behavior**
We expected for the "special" characters to display correctly, the html page has the charset="utf-8" so it is strange that the default text is not decoded but if you supply it in a translation in the config file it is properly displayed.

**Comment by adewes** [comment]
Hi @tommy-snellman! Sorry for the slight delay, I tried reproducing the issue with the development version of Klaro and there the translations seem to work fine:

![image](https://user-images.githubusercontent.com/550026/93802689-134cd700-fc44-11ea-8dc4-1903f1de64d6.png)

I suspect this to be an encoding issue. There could be several reasons for this:

- The encoding of your HTML page is not specified correctly. Please make sure you have the appropriate `<meta charset="utf-8">` tag on your site.
- Your web server could return the wrong encoding for the Klaro JS file. You can verify this by opening the developer tab, reloading your site and checking the headers of the Klaro script tag in the "Network" tab. The Klaro script is encoded as UTF-8, so make sure your server returns that as well.

From the information I have the most likely error source is that the web page is not set to the right encoding. Do you have a link to a site that I could inspect? You can also send me an e-mail to klaro@kiprotect.com if you don't want to post this publicly.

I'm not able to debug this further otherwise.

**Comment by adewes** [comment]
Hey @tommy-snellman, I can't do more to debug this issue right now, if you're still having trouble and can provide more debugging information please let me know and I'll reopen this.

**Comment by tommy-snellman** [comment]
The issue was fixed by calling the cdn in the script instead of having the klaro-no-css.js locally. Not sure why it did not work when using a local .js file because we made sure it was in UTF8 encoding but still did not work.

**Comment by adewes** [comment]
Ok great, glad you could resolve this issue! Seems weird indeed, I'll test this again with the No-CSS version of Klaro to make sure it works as expected.
