### ISSUE TITLE
Firefox (80.0.1) throws error on klaro.show()

### ISSUE THREAD

**Issue by okroener** [kiprotect/klaro#299]
When I call klaro.show() in Firefox the dialog appears for less than a second, hardly to see, and a page is show with the content:

"false"

In Edge, Chrome etc no error occurs.

**Comment by adewes** [comment]
Hey @okroener! Can you please provide a link to the site where Klaro is installed, or a config and full JS/HTML snippet. I can't debug this otherwise.

**Comment by okroener** [comment]
Hey @adewes! Sure, the link is as follows:

Website: [https://profile.oliver-kroener.de/#/](https://profile.oliver-kroener.de)
Config: [https://profile.oliver-kroener.de/js/config.js](https://profile.oliver-kroener.de/js/config.js)

And the code snippet is:

`<q-btn fab color="secondary" icon="settings" label="Cookie Settings" type='a' href='javascript:klaro.show();' />`

I am using a [https://quasar.dev/](https://quasar.dev) SPA.

Many thanks in advance!

**Comment by adewes** [comment]
Thanks! So it seems that some other script is interfering with the Klaro onclick handler and render the return value of the Klaro `show()` function (which is `false`).

In general I'd avoid using a `href="javascript:..."` tag (see e.g. here for a reasoning - https://stackoverflow.com/questions/3498492/javascriptvoid0-vs-return-false-vs-preventdefault). Since you simply want to trigger JS here I'd use `onclick="klaro.show()"`, which for me works as intended. I can't say which other third-party script is interfering with the click handler here but there are **a lot** of handlers installed:

![image](https://user-images.githubusercontent.com/550026/93883521-f961d180-fce1-11ea-94f0-d34d6938462b.png)

Hope this solves your problem, if not please let me know.

**Comment by okroener** [comment]
Thank you very much!

The `onclick=...` works fine and as you mentioned its recommended as well.

There are "lot of handlers" and it interesting that only Firefox had an issue, but now it working on all browsers.

Thanks for your help and for providing that brilliant cookie consent module.

Have a nice day!
