### ISSUE TITLE
Klaro cookie deleted after navigation when default mandatory cookies are accepted

### ISSUE THREAD

**Issue by jmalarcon** [kiprotect/klaro#319]
**Steps to reproduce**

1. Define a few cookies in your Klaro `config.js` file, and make one or two of them `default: true` and `required: true`, and the rest of them `required: false` and `optOut: false`.
2. Launch your app and press the `Let me choose...` button.
3. In the modal dialog just click the `Accept selected` button without changing any switch. You're accepting the preselected mandatory cookies with this action and Klaro creates a cookie to save your settings, making the dialogs dissappear.
4. Refresh the page or navigate to a different page: the Klaro cookie gets deleted and it shouldn't!
5. Navigate to a different page or refresh the page again: the cookies notice shows up again because there's no Klaro cookie.

You can see this in action in [this 21 seconds video](https://share.getcloudapp.com/o0umKrpX).

I've created a minimal functional example for you to try. You can download it [here](https://p157.p1.n0.cdn.getcloudapp.com/items/QwukBP4o/klaro-def-cookies.zip?v=6f84164ebfe5d5f9470589f93c25a2a1). It's just a minimal page, a `config.js` file and the Klaro scripts.

**Current behavior**

The Klaro cookie gets deleted if you don't change the default settings in the modal dialog, even if some cookies are selected.

**Expected behavior**

The Klaro cookie will be kept in the browser after being set for the first time.

Thanks for your great work!

**Comment by adewes** [comment]
Hi @jmalarcon! Thanks for opening this issue and for documenting this so thoroughly. We should probably be more clear about the meaning of the cookie config. The problem is here:

```
        {
            name: 'yt',
            title: 'YouTube',
            purposes: ['analytics'],
            cookies: [
                [/.*/, '/', 'www.youtube.com']
            ],
            required: false,
            optOut: false
        }
```

Klaro will match cookies based on the regular expression you provided (`.*`), which will match **all** cookies that can be accessed via Javascript (which includes the Klaro cookie). The `domain` and `path` arguments are necessary for Klaro to delete the cookie, they will not be used for matching cookies (in fact, they are not even exposed by the browser: https://stackoverflow.com/questions/2959010/how-to-get-the-domain-value-for-a-cookie-in-javascript).

Another problem is that you try to delete cookies for the domain `www.youtube.com`. For domains other than Youtube itself these are so-called third-party cookies, so you can't access or delete them via Javascript from another domain, and Klaro cannot manage them.

We'll soon provide a context-based consent mechanism for Youtube btw, then you won't have to manage these things manually anymore. Thanks again for reporting this, and let me know if I can help with anything else.

**Comment by jmalarcon** [comment]
Thank you very much Andreas!

I thought that the regular expression applied only to the domain in question, but didn't thought about the cross-domain cookie access and not being able to access secured HTTP cookies from JavaScript. My fault 🤦‍♂️

So, to be clear, one must only set the `cookies` property for your domain or any subdomains of it, isn't it? In services that set cookies in third party domains it's better not to set the `cookies` section.

Thanks again!

**Comment by adewes** [comment]
Hey @jmalarcon, no problem, as I said I think we need to make this more clear in the documentation. Yes, Klaro can only manage first-party, Javascript-accessible cookies (so no `HTTPOnly` cookies either).

We're working on a way to manage `HTTPOnly` first-party cookies as well, this will require API functionality though.
