### ISSUE TITLE
Not understand config.js

### ISSUE THREAD

**Issue by net4u** [KIProtect/klaro#37]
Not sure what may come here (in place of klaro.kiprotect.com):
``// A list of regex expressions or strings giving the names of
            // cookies set by this app. If the user withdraws consent for a
            // given app, Klaro will then automatically delete all matching
            // cookies.
            cookies : [
                // you can also explicitly provide a path and a domain for
                // a given cookie. This is necessary if you have apps that
                // set cookies for a path that is not "/" or a domain that
                // is not the current domain. If you do not set these values
                // properly, the cookie can't be deleted by Klaro
                // (there is no way to access the path or domain of a cookie in JS)
                [/^_pk_.*$/, '/', 'klaro.kiprotect.com'], //for the production version
                [/^_pk_.*$/, '/', 'localhost'], //for the local version
                'piwik_ignore'],

Is place for the url of the site or the url of my matomo (e.g. www.mysite.com or e.g. analytics.my-matomo.com)

Also I don't understand clear how to deal with Google Analytics: it falls under inline tracker, external tracker or what? (anyway I found that the only cookies set by my site are related to Matomo, I found noting related to GA.

Thnx

**Comment by adewes** [comment]
Hi @net4u , the config is just an example, so if you don't use Google Analytics you don't need to include it in the list of course. Concerning the `path` and `domain` values: These are necessary when the cookies are not set for the root directory (`/`) of the current domain. The reason is that we can only delete cookies via JS if we specify the *exact* path and domain of the cookie, and unfortunately we can't read these out programatically, which means you need to provide them by hand.
You can do this by opening the site for which you want to enable Klaro, then opening the developer console in your browser (Chrome, Firefox or Safari), browsing to the "Cookies" section and checking the path and domain for the cookies that are set when you click on "accept" (or before you install Klaro). You can then put these values into the config to enable Klaro to remove these cookies.
Let me know if this helps, if it answers your question feel free to close this issue.

**Comment by net4u** [comment]
thnx. I found the path for matomo being "/" so I understand that I have nothing to change about this.
I use both Matomo and GA, but I found only cookies set by Matomo, nothing set by GA. But I use GA. I don't understand where falls GA: inline or external.
In fact I use matomo, GA, google maps, google fonts, fontawsome and bootstrap, but only Matomo it seems to me that it sets cookies.

**Comment by adewes** [comment]
I'm closing this issue do to inactivity, please feel free to reopen it if you think you're problem is not solved.
