### ISSUE TITLE
Building Klaro from scratch

### ISSUE THREAD

**Issue by BitchCO** [KIProtect/klaro#55]
Hi!
When I try to build my own version of Klaro it gives me this error: http://prntscr.com/lt0qa1

Any help is appreciated.

P.S. I'm using Windows, so I don't know if that is a issue...

**Comment by BitchCO** [comment]
Update: tried same thing on Mac. It work's, so it is Windows related issue.
Hoping it's gonna get updated.

**Comment by adewes** [comment]
OK great! Currently we don't explicitly support Windows or Mac, glad it works on Mac though.

**Comment by BitchCO** [comment]
Any idea how can I build it on Windows?

**Comment by adewes** [comment]
Honestly no, sorry :/ We work exclusively on Linux and can't provide much support. The problem here just seems to be that Windows does not support passing environment variables to scripts, which we use to e.g. automatically tag the git version. You can e.g. use Cygwin to get a fully featured shell environment on Windows (or Windows subsystem for Linux), or you can modify the Webpack config.
